; PlatformIO Project Configuration File
;
; CCR3 - Chinese Chess Robot Firmware
;

[env:mega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino

monitor_speed = 115200

lib_deps =
    ; Thêm thư viện cần thiết
    ; AccelStepper
    ; Servo

build_flags =
    -D DEBUG_MODE=0
